version: '3'

services:
  tera-admin:
    env_file: ../.env
    image: ${TERA_ADMIN}:latest
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile_tera-admin

  tera-www:
    env_file: ../.env
    image: ${TERA_WWW}:latest
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile_tera-www
